### ISSUE TITLE
Implement "innapropriate/offensive image" flag functionality

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/pigeonhole#10]
Mark record as hidden via POST to ecodata with JSON:
`{ "offensiveFlag":true }`

**Comment by djtfmartin** [comment]
I think this is done.

**Comment by nickdos** [comment]
This is now open again after I made changes to simplify the linking to taxon overflow to remove the (redundant) interactive popup (goes straight through without interaction). So we might need an additional flag for this after all?This is now open again after I made changes to simplify the linking to taxon overflow to remove the (redundant) interactive popup (goes straight through without interaction). So we might need an additional flag for this after all?
