### ISSUE TITLE
SDS check on record pre-submission

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/pigeonhole#11]
We need to add an SDS check on record pre-submission. We should do this before we release to production.

**Comment by djtfmartin** [comment]
Assigning back to me. Realised the service isnt working on top of the biocache because we disabled adhoc sampling.

**Comment by nickdos** [comment]
Please post the details of the service so I can implement the client end of this.

**Comment by djtfmartin** [comment]
its the validate() service

https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/master/grails-app/controllers/au/org/ala/pigeonhole/SightingsController.groovy

Its a http post with json body:

{"decimalLatitude":-33.1342324324,"decimalLongitude":122.123423423423, "scientificName":"Calyptorhynchus (Zanda) latirostris"}

**Comment by djtfmartin** [comment]
example output

https://www.dropbox.com/s/toz7gap8zbih4lb/Screenshot%202015-04-07%2012.38.45.png?dl=0

**Comment by nickdos** [comment]
I've got a first pass working and I'm only checking the fields:
- `habitatMismatch`
- `outlierForExpertDistribution`
- `sensitive`

Are there others I should check?
Also, we'll have to skip this test if no `scientificName` is specified (its optional).
Should we pass the values of these checks (or anything) onto `ecodata` to indicate location was checked?

**Comment by djtfmartin** [comment]
Are there others I should check?
**no, thats it for now.**

Also, we'll have to skip this test if no scientificName is specified (its optional).
**yes, nothing we can do in this case**

Should we pass the values of these checks
**sounds like a good idea to just store them**

**Comment by nickdos** [comment]
Still TO DO:
- store and forward pre-submission check data onto `ecodata`.

Not sure this is all that valuable so making a lower priority.
