### ISSUE TITLE
Grid view for images

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/pigeonhole#12]
Add a grid view for images to

http://pigeonhole-dev.ala.org.au/recent

Similar to what we have done for the lists tool 

e.g. http://lists.ala.org.au/speciesListItem/list/dr781#grid

**Comment by nickdos** [comment]
http://pigeonhole-dev.ala.org.au/recent

Only 2 of the 10 sightings here have images and one of them has 18 images... 

Not sure how a grid view will work, as most of the info is text... We'll have to lose many fields and I don't know which to include. Also do we show only one of the 18 images for the single sighting? Seems a backwards step to me. 

In essence, I'm not convinced this is a useful change - unless we make having an image mandatory.

**Comment by djtfmartin** [comment]
i see what you mean.
The consistent bit of feedback on that page (/recent) was to make the images more prominent and reduce the text. 
Any ideas ?

**Comment by nickdos** [comment]
I'll try putting the image at start of row and simplify the text/rows so that its less like a table and more "grid like"
