### ISSUE TITLE
Answer/views/date buttons to have ascending/descending indicator toggle 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/pigeonhole#13]

**Comment by nickdos** [comment]
I presume this is to sort the order of sightings in the recent/my_sightings list?

Not sure this is possible as its a separate AJAX call to include buttons and the list sorting is handled in the grails backend (ecodata actually).

**Comment by djtfmartin** [comment]
Yes to order the sightings. 

Perhaps this is something for the next milestone.
