### ISSUE TITLE
Dev phases

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/pigeonhole#2]
4a. pigeonhole

phase 1 - Nick - 4 weeks
initial page where user select species group, or thematic list (e.g. Weeds)
allow user to specify a location
show images of taxon from the specified group recorded in an area within an adjustable time frame)
show recent records for the selected taxon
environmental outlier check

phase 2 - Nick & Chris - 2 weeks
integration with ecodata for record submission

phase 3 - Nick & Dave B - 2 weeks
integration with taxonoverflow for identification workflow and results

**Comment by djtfmartin** [comment]
closing. no longer relevant
