### ISSUE TITLE
Edit and adding new images to existing record breaks links

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/pigeonhole#21]
To reproduce on http://pigeonhole-dev.ala.org.au:
1. Submit a record with an image
2. Edit the record and add a new image & submit

Image display becomes broken in the /recent display and on the Edit screen (on selecting to edit a second time).

Image URLs become:

"http://images-dev.ala.org.au/image/proxyImageThumbnailLarge?imageId=d8484dae-fe9c-4c03-9725-cb3eed8fe3d9,http://pigeonhole-dev.ala.org.au/uploads/image_117726e9-df51-430f-96e1-399358387ac9.jpg"

![screenshot 2015-06-17 16 28 08](https://cloud.githubusercontent.com/assets/444897/8211293/28895828-150e-11e5-84a4-4dc1d9df0ee1.png)

**Comment by djtfmartin** [comment]
Digging deeper, this is a bug with the javascript.

The JS maintains hidden fields for each of the images

<input type="hidden" class="title" value="" name="multimedia[0].title">

and the problems arise when adding new images to a record that already has images because the same index (multimedia[idx]) is getting used for 2 images.

**Comment by nickdos** [comment]
Just tested on pigeonhole-dev.ala.org.au and now works. Tested replacing image, adding image, new sighting, add two images and then remove first image before submitting.
