### ISSUE TITLE
Revert to Google maps baselayer

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/pigeonhole#29]
John la Salle has pointed out that the new sighting page does not allow the map to zoom in as far in the satelite view, than the previous version did. This is due to the change to use Open Street Map instead of Google. He also notes the address lookup is better with Google, as is the lat/lng to place name lookups.

Steps required:
- research usage rules for Google base layer inclusion in Leaflet tool
- research usage limits for Google base requests per month, etc.
- consider approaching Google to negotiate a possible agreement if required
- Implement baselayer change and geocoding lookups using Google if we able to do so.

**Comment by timrobertson100** [comment]
While it is technically possible, the G maps terms of service require you to use the G JS library to access G base layers. You can fairly easily use leaflet and swap to G maps JS only when a G layer is used - CartoDB is a good example of this.

**Comment by nickdos** [comment]
https://github.com/shramov/leaflet-plugins
and
https://github.com/shramov/leaflet-plugins/blob/master/examples/google.html

**Comment by timrobertson100** [comment]
It is technically possible but it breaks G terms of service.  See 10.1.1 on https://developers.google.com/maps/terms and they raise this in the Leaflet FAQ too in https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that

It is possible G will close the loophole at some point or issue an instruction to stop and I don't know if the ALA folks would be comfortable knowingly breaking terms of service.  

An alternative would be to support any slippy map JS format by abstracting over the underlying JS library - you can swap them in and out depending on the baselayer.  Carto.js might do all you need for that already here: https://github.com/CartoDB/cartodb.js/tree/develop/src/geo

Sorry - I'm not trying to be awkward.  Just trying to help answer the "research usage rules for Google base layer inclusion in Leaflet tool" part of this issue.

**Comment by timrobertson100** [comment]
A possible alternative option: How does the ESRI imagery fair for your part of the world, as it can be used with credit IIRC?  http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer?f=jsapi

**Comment by nickdos** [comment]
Also implement Google geocode and geolocate functions as requested by John LS.
