### ISSUE TITLE
can't add an image without the mandatory fields already being completed

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/pigeonhole#31]
If you click the "Add files" button, a list of errors appears:

There was a problem with one or more fields, please fix these errors (in red)
Species - Either species name is required OR one or more tags AND media files are both required
Date - Date is required
sighting.field.individualCount - individualCount is required
sighting.field.georeferenceProtocol - georeferenceProtocol is required

adding a date resets to blank if the Add files button is clicked again.

**Comment by nickdos** [comment]
I can't replicate this. Could you add the browser and version specs please?

**Comment by M-Nicholls** [comment]
Firefox 39.0, I'm still getting the same error
