### ISSUE TITLE
Fish skinned "identify" page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/pigeonhole#7]
We have good distribution shape files for fish species, thanks to the Fish Map tool (http://fish.ala.org.au). We could therefore simplify the UI to remove the "radius" option from the map section and use the given input location and test which species layers it intersects. 

This could be a test-bed for then going a step further and pre-generating predicted distribution layers for terrestrial species, based on the best 5 environmental layers in the SP.

**Comment by djtfmartin** [comment]
We also have shapes for birds & eventually ERIN threatened species.
